# Generated by Django 4.0.1 on 2022-01-16 15:53

import BioTours_Application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolphin_Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Species', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dolphin_Species',
                'verbose_name_plural': 'Dolphin_Species',
                'db_table': 'Dolphin_Species',
            },
        ),
        migrations.CreateModel(
            name='Prevalent_Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Behavior', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Prevalent_Behavior',
                'verbose_name_plural': 'Prevalent_Behaviors',
                'db_table': 'Prevalent_Behavior',
            },
        ),
        migrations.CreateModel(
            name='Research_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Research_Activity',
                'verbose_name_plural': 'Research_Activities',
                'db_table': 'Research_Activity',
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Port', models.CharField(default='Not available', max_length=100)),
                ('Date', models.DateField(help_text='Date Format: YYYY-MM-DD')),
                ('Start_Activity_Time', models.TimeField(blank=True, help_text='Time Format: HH:mm:ss', null=True)),
                ('End_Activity_Time', models.TimeField(blank=True, null=True)),
                ('Start_Contact_Time', models.TimeField(blank=True, null=True)),
                ('End_Contact_Time', models.TimeField(blank=True, null=True)),
                ('Latitude_Contact', models.FloatField(blank=True, help_text='The Equator has a latitude of 0°, the North Pole has a latitude of 90° North (+90°), and the South Pole has a latitude of 90° South (−90°). ', null=True, validators=[BioTours_Application.models.validate_latitude])),
                ('Longitude_Contact', models.FloatField(blank=True, help_text='Longitude is given as an angular measurement ranging from 0° at the Prime Meridian to +180° eastward and −180° westward.', null=True, validators=[BioTours_Application.models.validate_longitude])),
                ('Depth', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Number_Individuals', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Number_Calves', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Number of small dolphins', null=True)),
                ('Other_Boats', models.CharField(blank=True, default='Not available', max_length=100, null=True)),
                ('Fishing_Gear_Available', models.CharField(blank=True, default='Not available', max_length=100, null=True)),
                ('Interaction_With_Gear', models.CharField(blank=True, default='Not available', max_length=100, null=True)),
                ('Other_Organism', models.CharField(blank=True, default='Not available', max_length=100, null=True)),
                ('Notes', models.TextField(blank=True, default='Not available', null=True)),
                ('Activity', models.ManyToManyField(to='BioTours_Application.Research_Activity')),
                ('Behavior', models.ManyToManyField(to='BioTours_Application.Prevalent_Behavior')),
                ('First_Species_Observed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BioTours_Application.dolphin_species')),
                ('Second_Species_Observed', models.ManyToManyField(related_name='Second_Species_Observed', to='BioTours_Application.Dolphin_Species')),
            ],
            options={
                'verbose_name': 'Sighting',
                'verbose_name_plural': 'Sightings',
                'db_table': 'Sighting',
            },
        ),
        migrations.CreateModel(
            name='File_Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=BioTours_Application.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'jpg', 'png'])])),
                ('sighting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BioTours_Application.sighting')),
            ],
            options={
                'verbose_name': 'Sighting_File',
                'verbose_name_plural': 'Sighting_Files',
                'db_table': 'Sighting_File',
            },
        ),
    ]
