# Generated by Django 4.0.1 on 2022-01-21 15:43

import BioTours_Application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BioTours_Application', '0001_initial'),
    ]
