# Generated by Django 4.0.1 on 2022-01-21 16:02

import BioTours_Application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BioTours_Application', '0002_gallery_alter_file_sighting_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_gallery', models.FileField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'jpg', 'png', 'jpeg'])])),
            ],
            options={
                'verbose_name': 'Gallery_Files',
                'verbose_name_plural': 'Gallery_Files',
                'db_table': 'Gallery_File',
            },
        ),
        migrations.AlterField(
            model_name='file_sighting',
            name='file',
            field=models.FileField(upload_to=BioTours_Application.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='file_sighting',
            name='sighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BioTours_Application.sighting'),
        ),
    ]
