# Generated by Django 4.0.1 on 2022-01-22 11:15

import BioTours_Application.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioTours_Application', '0003_gallery_alter_file_sighting_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='Gps_Location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='file_sighting',
            name='file',
            field=models.FileField(upload_to=BioTours_Application.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'jpg', 'png', 'jpeg']), BioTours_Application.models.file_size]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='file_gallery',
            field=models.FileField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'jpg', 'png', 'jpeg']), BioTours_Application.models.file_size]),
        ),
    ]
